import type { Listing, PhotoPlaceholder } from "@/types";

/**
 * Construye los placeholders de foto de un alojamiento. Cada tripleta es
 * [etiqueta, color inicial, color final] del degradado.
 */
const photos = (
  id: string,
  entries: [string, string, string][],
): PhotoPlaceholder[] =>
  entries.map(([label, from, to], index) => ({
    id: `${id}-${index + 1}`,
    label,
    from,
    to,
  }));

/**
 * Datos simulados. En un proyecto real esto llegaría de una API; aquí se sirve
 * desde memoria y las páginas fingen la latencia con `setTimeout`.
 */
export const LISTINGS: Listing[] = [
  {
    id: "casa-acantilado-nerja",
    title: "Casa del Acantilado",
    location: "Nerja, Málaga",
    pricePerNight: 142,
    rating: 4.92,
    reviewsCount: 218,
    categoryId: "beach",
    availability: "5-10 de mar",
    isGuestFavorite: true,
    coordinates: { lat: 36.7452, lng: -3.8748 },
    photos: photos("casa-acantilado-nerja", [
      ["Vista al mar desde la terraza", "#0ea5e9", "#0f172a"],
      ["Salón con ventanales", "#f8fafc", "#94a3b8"],
      ["Dormitorio principal", "#fef3c7", "#d97706"],
      ["Terraza al atardecer", "#fb7185", "#7c2d12"],
      ["Cocina abierta", "#e2e8f0", "#475569"],
    ]),
  },
  {
    id: "villa-miramar-marbella",
    title: "Villa Miramar",
    location: "Marbella, Málaga",
    pricePerNight: 480,
    rating: 4.85,
    reviewsCount: 96,
    categoryId: "mansion",
    availability: "12-18 de mar",
    isGuestFavorite: false,
    coordinates: { lat: 36.5099, lng: -4.8863 },
    photos: photos("villa-miramar-marbella", [
      ["Fachada de la villa", "#fde68a", "#b45309"],
      ["Piscina infinita", "#38bdf8", "#0c4a6e"],
      ["Salón de doble altura", "#f1f5f9", "#64748b"],
      ["Jardín mediterráneo", "#4ade80", "#14532d"],
    ]),
  },
  {
    id: "atico-vistas-madrid",
    title: "Ático con vistas a Gran Vía",
    location: "Madrid",
    pricePerNight: 118,
    rating: 4.78,
    reviewsCount: 341,
    categoryId: "city",
    availability: "2-7 de mar",
    isGuestFavorite: true,
    coordinates: { lat: 40.4203, lng: -3.7058 },
    photos: photos("atico-vistas-madrid", [
      ["Skyline desde el balcón", "#f97316", "#431407"],
      ["Salón con sofá gris", "#e5e7eb", "#4b5563"],
      ["Dormitorio luminoso", "#fef9c3", "#a16207"],
      ["Baño reformado", "#cbd5e1", "#334155"],
    ]),
  },
  {
    id: "cabana-pinos-cercedilla",
    title: "Cabaña de los Pinos",
    location: "Cercedilla, Madrid",
    pricePerNight: 96,
    rating: 4.95,
    reviewsCount: 127,
    categoryId: "cabin",
    availability: "20-25 de mar",
    isGuestFavorite: true,
    coordinates: { lat: 40.7411, lng: -4.0553 },
    photos: photos("cabana-pinos-cercedilla", [
      ["Cabaña entre pinos", "#16a34a", "#052e16"],
      ["Chimenea encendida", "#f59e0b", "#7c2d12"],
      ["Dormitorio abuhardillado", "#fef3c7", "#92400e"],
      ["Porche de madera", "#a3a3a3", "#3f3f46"],
    ]),
  },
  {
    id: "cortijo-olivar-ronda",
    title: "Cortijo El Olivar",
    location: "Ronda, Málaga",
    pricePerNight: 165,
    rating: 4.88,
    reviewsCount: 74,
    categoryId: "countryside",
    availability: "8-14 de mar",
    isGuestFavorite: false,
    coordinates: { lat: 36.7413, lng: -5.1663 },
    photos: photos("cortijo-olivar-ronda", [
      ["Olivar al amanecer", "#84cc16", "#365314"],
      ["Patio encalado", "#fafaf9", "#78716c"],
      ["Salón con vigas", "#fed7aa", "#7c2d12"],
      ["Vistas al tajo", "#60a5fa", "#1e3a8a"],
    ]),
  },
  {
    id: "loft-born-barcelona",
    title: "Loft del Born",
    location: "Barcelona",
    pricePerNight: 210,
    rating: 4.81,
    reviewsCount: 452,
    categoryId: "trending",
    availability: "1-6 de mar",
    isGuestFavorite: true,
    coordinates: { lat: 41.3851, lng: 2.1834 },
    photos: photos("loft-born-barcelona", [
      ["Loft de ladrillo visto", "#d97706", "#451a03"],
      ["Cocina industrial", "#e4e4e7", "#3f3f46"],
      ["Dormitorio en altillo", "#fecdd3", "#881337"],
      ["Calle del Born", "#fbbf24", "#78350f"],
    ]),
  },
  {
    id: "casa-lagar-mijas",
    title: "Casa Lagar con piscina privada",
    location: "Mijas, Málaga",
    pricePerNight: 275,
    rating: 4.9,
    reviewsCount: 158,
    categoryId: "pool",
    availability: "15-21 de mar",
    isGuestFavorite: true,
    coordinates: { lat: 36.5959, lng: -4.6374 },
    photos: photos("casa-lagar-mijas", [
      ["Piscina privada", "#22d3ee", "#155e75"],
      ["Porche con hamacas", "#fde68a", "#a16207"],
      ["Salón abierto al jardín", "#f5f5f4", "#57534e"],
      ["Dormitorio con terraza", "#e0f2fe", "#0369a1"],
    ]),
  },
  {
    id: "refugio-lago-sanabria",
    title: "Refugio junto al lago",
    location: "Sanabria, Zamora",
    pricePerNight: 88,
    rating: 4.97,
    reviewsCount: 63,
    categoryId: "lake",
    availability: "22-27 de mar",
    isGuestFavorite: true,
    coordinates: { lat: 42.1194, lng: -6.7042 },
    photos: photos("refugio-lago-sanabria", [
      ["Lago al amanecer", "#38bdf8", "#0f172a"],
      ["Embarcadero de madera", "#a8a29e", "#292524"],
      ["Salón con estufa", "#fbbf24", "#78350f"],
      ["Bosque de robles", "#4ade80", "#14532d"],
    ]),
  },
  {
    id: "apartamento-triana-sevilla",
    title: "Apartamento en Triana",
    location: "Sevilla",
    pricePerNight: 105,
    rating: 4.83,
    reviewsCount: 289,
    categoryId: "trending",
    availability: "3-9 de mar",
    isGuestFavorite: false,
    coordinates: { lat: 37.3833, lng: -6.0025 },
    photos: photos("apartamento-triana-sevilla", [
      ["Balcón sobre el Guadalquivir", "#fb923c", "#7c2d12"],
      ["Salón con azulejos", "#bae6fd", "#075985"],
      ["Dormitorio blanco", "#fafafa", "#71717a"],
      ["Puente de Triana", "#facc15", "#713f12"],
    ]),
  },
  {
    id: "casa-piedra-cudillero",
    title: "Casa de piedra frente al puerto",
    location: "Cudillero, Asturias",
    pricePerNight: 132,
    rating: 4.91,
    reviewsCount: 112,
    categoryId: "countryside",
    availability: "10-15 de mar",
    isGuestFavorite: false,
    coordinates: { lat: 43.5622, lng: -6.1447 },
    photos: photos("casa-piedra-cudillero", [
      ["Puerto de Cudillero", "#38bdf8", "#164e63"],
      ["Muros de piedra", "#d6d3d1", "#44403c"],
      ["Cocina con leña", "#fed7aa", "#7c2d12"],
      ["Acantilados verdes", "#22c55e", "#14532d"],
    ]),
  },
  {
    id: "villa-sa-punta-ibiza",
    title: "Villa Sa Punta",
    location: "Ibiza, Baleares",
    pricePerNight: 620,
    rating: 4.87,
    reviewsCount: 88,
    categoryId: "mansion",
    availability: "18-24 de mar",
    isGuestFavorite: false,
    coordinates: { lat: 38.9067, lng: 1.4206 },
    photos: photos("villa-sa-punta-ibiza", [
      ["Villa blanca sobre el mar", "#f8fafc", "#0ea5e9"],
      ["Piscina al atardecer", "#f472b6", "#701a75"],
      ["Chill out exterior", "#fdba74", "#7c2d12"],
      ["Suite principal", "#e2e8f0", "#475569"],
    ]),
  },
  {
    id: "estudio-playa-gran-canaria",
    title: "Estudio a 2 min de la playa",
    location: "Maspalomas, Gran Canaria",
    pricePerNight: 74,
    rating: 4.69,
    reviewsCount: 503,
    categoryId: "beach",
    availability: "6-11 de mar",
    isGuestFavorite: false,
    coordinates: { lat: 27.7606, lng: -15.586 },
    photos: photos("estudio-playa-gran-canaria", [
      ["Dunas de Maspalomas", "#fcd34d", "#92400e"],
      ["Estudio compacto", "#f4f4f5", "#52525b"],
      ["Terraza con vistas", "#7dd3fc", "#0c4a6e"],
      ["Paseo marítimo", "#fb7185", "#881337"],
    ]),
  },
];
